Fix testrunner for Python 3.8/Linux
When running tests with Python 3.8/Linux, the existence_test fails:

File "pyside-setup/sources/pyside2/tests/registry/existence_test.py", line 73
    from init_platform import enum_all, generate_all
File "pyside-setup/sources/pyside2/tests/registry/init_platform.py", line 59
    from util import get_refpath, get_script_dir
File "pyside-setup/sources/pyside2/tests/registry/util.py", line 113
    platform_name = "".join(distro.linux_distribution()[:2]).lower()
AttributeError module 'platform' has no attribute 'linux_distribution'

since platform.linux_distribution() was removed in 3.8. Extract
into a separate method and warn to install distro.

Task-number: PYSIDE-939
Change-Id: I42d04830d51563cc3fbaddc3941c927402514480
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>