QtQml tests: Add parentheses around print
Fixes syntax errors in Python 3:
SyntaxError: Missing parentheses in call to 'print'

Task-number: PYSIDE-431
Change-Id: I076dc0f07dc7d3e55dea59dcfa8026fd49862d9c
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>