ApiExtractor/tests: Fix a number of C++ errors in the test code
* testTemplateOnContainers(): Error:unknown type name 'QList'
  TestTemplates::testTemplateWithNamespace(): Error:unknown type name 'QList'

Added dummy definition.

* TestTemplates::testTemplateValueAsArgument():
  TestTemplates::testTemplatePointerAsArgument():
  TestTemplates::testTemplateReferenceAsArgument():
    main.cpp:1:38:Error:expected unqualified-id
    main.cpp:1:61:Error:expected ')'
    main.cpp:1:61:Error:variable has incomplete type 'List'
    1:    template<typename T> struct List() {};    void func(List<int> arg) {}

Removed braces.

* testContainerTypeIncompleteArgument():
    main.cpp:1:203:Error:use of class template 'Vector' requires template arguments
    main.cpp:1:217:Error:use of undeclared identifier 'T'
    main.cpp:1:221:Warning:extra qualification on member 'otherMethod'

Added template <typename T> above method.

* TestRemoveOperatorMethod::testRemoveOperatorMethod():
    unknown type name '__int64'
    main.cpp:1:365:Error:expected ')'
    main.cpp:1:451:Error:unknown type name 'Char'
    main.cpp:1:480:Error:unknown type name 'ByteArray'
    main.cpp:1:514:Error:unknown type name 'String'

Moved struct definitions above, removed ambiguous long and use standard
typedefs from stdint.h.
Note: The unsigned __int64 was not recognized by the old code model.

* TestAbstractMetaClass::testAbstractClassDefaultConstructors()
  Error:C++ requires a type specifier for all declarations

Added void to method.

* testEnum::testEnumCppSignature()
    main.cpp:1:73:Error:member 'A' has the same name as its class

Renamed inner enumeration values.

* TestFunctionTag::testFunctionTagForSpecificSignature()

Added missing ';'.

Change-Id: I2c2ce90b0b7a49d4aef40b1adf5f683feceb8d63
Reviewed-by: Christian Tismer <tismer@stackless.com>