qfile_test.py: Fix Python 3
- Make the check in testBug721 depending on Python version.
- Ensure cleanup of the temporary file in case of test failure,
  fixing windows warning:
  File "tests/QtCore/qfile_test.py", line 21, in tearDown
    os.remove(self.filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'd:\\temp\\tmp27nmak6m'

Change-Id: Ie69de51658109f5a9e649f9377b686a6a291cfe0
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>