1. These 2 new functions could be suppressed by editing PySide2/QtTest/typesystem_test.xml 2. Also fixed typo: Qt5Webkit -> Qt5WebKit 3. fixed global.h.in (@Qt5WebEngine_FOUND@ should be @Qt5WebEngineWidgets_FOUND@) 4. And fixed a couple of crash (more condition check).
`Scanning dependencies of target QtTest
[ 82%] Building CXX object PySide2/QtTest/CMakeFiles/QtTest.dir/PySide2/QtTest/qtest_pysideqtoucheventsequence_wrapper.cpp.o
[ 82%] Building CXX object PySide2/QtTest/CMakeFiles/QtTest.dir/PySide2/QtTest/qtest_wrapper.cpp.o
/Volumes/data2/mayadev/pyside/2.0qt56/pyside2-setup/pyside_build/py2.7-qt5.6.0-64bit-release/pyside2/PySide2/QtTest/PySide2/QtTest/qtest_wrapper.cpp:3836:40: error: expected ';' after top
level declarator
static PyObject* Sbk_QTestFunc_toString(PyObject* self, PyObject* pyArg)
^
;
/Volumes/data2/mayadev/pyside/2.0qt56/pyside2-setup/pyside_build/py2.7-qt5.6.0-64bit-release/pyside2/PySide2/QtTest/PySide2/QtTest/qtest_wrapper.cpp:4120:7: error: unexpected namespace name
'QTest': expected expression
::QTest* cppSelf = 0;
^
/Volumes/data2/mayadev/pyside/2.0qt56/pyside2-setup/pyside_build/py2.7-qt5.6.0-64bit-release/pyside2/PySide2/QtTest/PySide2/QtTest/qtest_wrapper.cpp:4120:14: error: use of undeclared
identifier 'cppSelf'
::QTest* cppSelf = 0;
^
/Volumes/data2/mayadev/pyside/2.0qt56/pyside2-setup/pyside_build/py2.7-qt5.6.0-64bit-release/pyside2/PySide2/QtTest/PySide2/QtTest/qtest_wrapper.cpp:4121:16: error: use of undeclared
identifier 'cppSelf'
SBK_UNUSED(cppSelf)
^
/Volumes/data2/mayadev/pyside/2.0qt56/pyside2-setup/pyside_install/py2.7-qt5.6.0-64bit-release/include/shiboken2/helper.h:31:31: note: expanded from macro 'SBK_UNUSED'
#define SBK_UNUSED(x) (void)x;
^
/Volumes/data2/mayadev/pyside/2.0qt56/pyside2-setup/pyside_build/py2.7-qt5.6.0-64bit-release/pyside2/PySide2/QtTest/PySide2/QtTest/qtest_wrapper.cpp:4124:5: error: use of undeclared
identifier 'cppSelf'
cppSelf = ;
^
/Volumes/data2/mayadev/pyside/2.0qt56/pyside2-setup/pyside_build/py2.7-qt5.6.0-64bit-release/pyside2/PySide2/QtTest/PySide2/QtTest/qtest_wrapper.cpp:4124:15: error: expected expression
cppSelf = ;

`

The toString and toString errors are caused by changes in QtTest/qtestcase.h

#define QTEST_COMPARE_DECL(KLASS)\
template<> Q_TESTLIB_EXPORT char *toString(const KLASS &);

Qt 5.6 has the following new lines in qtestcase.h:
QTEST_COMPARE_DECL(signed char)
QTEST_COMPARE_DECL(unsigned char)

shiboken picked up the new functions in Qt 5.6

These 2 new functions could be suppressed by editing PySide2/QtTest/typesystem_test.xml