abstractmetabuilder_p.h: Fix compilation with some versions of g++
Fix the return type, which caused complaints by some versions of g++:

sources/shiboken2/ApiExtractor/abstractmetabuilder_p.h: In member function 'ScopeModelItem AbstractMetaBuilderPrivate::popScope()':
sources/shiboken2/ApiExtractor/abstractmetabuilder_p.h:61:57: error: could not convert 'QList<T>::takeLast() [with T = QSharedPointer<_NamespaceModelItem>]()' from 'QSharedPointer<_NamespaceModelItem>' to 'QSharedPointer<_ScopeModelItem>'

Change-Id: I94abdfb9d76d3f0078e198b4230129150d2f43ea
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>