Fixed shibokengenerator.cpp In shibokengenerator.cpp, guessScopeForDefaultValue() think that NULL is a member of QJsonParseError and prefix it with QJsonParseError::“NULL” should not be prefixed..
It’s caused by prefixing the qualified class name to NULL constant in qjsondocument_wrapper.cpp
::QJsonParseError* cppArg1 = QJsonParseError::NULL;

[ 10%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/q jsonarray_wrapper.cpp.obj qjsonarray_wrapper.cpp [ 10%] Building CXX object PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/q jsondocument_wrapper.cpp.obj qjsondocument_wrapper.cpp D:\PySide2NewGit\pyside_build\py2.7-qt5.6.0-64bit-release\pyside2\PySide2\QtCore \PySide2\QtCore\qjsondocument_wrapper.cpp(346) : error C2589: 'constant' : illegal token on right side of '::' D:\PySide2NewGit\pyside_build\py2.7-qt5.6.0-64bit-release\pyside2\PySide2\QtCore \PySide2\QtCore\qjsondocument_wrapper.cpp(346) : error C2059: syntax error : '::'