Fix inheritance_diagram.py to run with Python3
- Fix _class_info() to return a real list instead
  of list view, fixing:
  TypeError: can't pickle dict_values objects
- Enclose font names in quotes, fixing dot complaining
  about a syntax error.
- Encode the hash string get_graph_hash(), fixing
  TypeError: Unicode-objects must be encoded before hashing
- Pass on options as dict instead of list to render_dot_html(),
  render_dot_latex()

Task-number: PYSIDE-363
Task-number: PYSIDE-617
Change-Id: If050b73cf35ac6a6c58c0d3e5ea713c736ea842c
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>