Fix wheel_override error when wheel not available
Since the try failed, there was no option to import DistUtilsCommandMixin
and then a:
    NameError: name 'DistUtilsCommandMixin' is not defined
and
    AttributeError: type object 'type' has no attribute 'user_options'
was raised.

Task-number: PYSIDE-807
Change-Id: If5aa37ce9928a5c029b21decc24bd2bccf9b4dc4
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>