Fix running scriptableapplication in a virtualenv on Linux with Python 3.8
Remove the environment setting introduced by
435bc2744cd108efc1511bf17117bd4f0de15b43 for Linux.
It is required for Windows only due to the changed
library load policy. On Linux, it causes:

Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Task-number: PYSIDE-1236
Change-Id: I58e71f877b6cb754290a4d0ae41518255181fafc
Reviewed-by: Christian Tismer <tismer@stackless.com>