scriptable application/Unix: Remove setting of PYTHONHOME for virtualenv
On Linux, with 3.8, it causes an error in conjunction with virtualenv:
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Task-number: PYSIDE-841
Change-Id: Ibf1caa1a797faab5dd8e4bfa6eb23296bb7945a5
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit 05db21e661c6ba9eb69516cb1386bcbd431b7d2d)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>