Use Python 3 API when converting unsigned long long
The existing code written for Python 2 wrongly detected large
values of size_t as negative on Windows, causing
TestShiboken::testWrapInstance() to fail:

 ERROR: testWrapInstance (__main__.TestShiboken)
   File "module_test.py", line 51, in testWrapInstance
     obj = shiboken.wrapInstance(addr, ObjectType)
 OverflowError

Use the new API of Python 3 which takes care of checking for
negative values.

Task-number: PYSIDE-431
Change-Id: I16bee5385223a7baba81b112d800459becfd8df7
Reviewed-by: Christian Tismer <tismer@stackless.com>