Fix test QtWidgets/bug_722.py
The test used to fail with:
Traceback (most recent call last):
File "bug_722.py", line 47, in testQRealSignal
    effect.blurRadiusChanged['qreal'].connect(foo1.setValue) # check if qreal is a valid type
IndexError: Signature blurRadiusChanged(qreal) not found for signal: blurRadiusChanged

The signatures changes from setBlurRadius(qreal) (Qt 4) to
setBlurRadius(double) (Qt 5) due to the metaobject resolving
types.

Task-number: PYSIDE-431
Change-Id: I240aac7adf34220a2e1016a0ba5ed78f5f51753b
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>