Fix testReverseOperators::testReverseSumWithAmbiguity()
The test was marked QEXPECT_FAIL() since the code snippet does not
compile with clang:

main.cpp:7:9: error: overloaded 'operator-' must have at least one parameter of class or enumeration type
main.cpp:8:9: error: overloaded 'operator/' must have at least one parameter of class or enumeration type

With Clang 10, the compiler even crashes on Windows.
Remove the offending part.

Change-Id: I3d954f19884e42b61dcfc2e7a9ec4f2a31fd432b
Reviewed-by: Christian Tismer <tismer@stackless.com>